### ISSUE TITLE
hardwares

### ISSUE THREAD

**Issue by gilgamsh** [Tsinghua-MARS-Lab/DenseTNT#13]
I'm wondering how much time you train the model.
In fact ,i plan to train the model with two 2080ti  but found it takes a lot of time to train(2h /epoch) and i found that it seems that the gpu utility is always low . is that a problem about the code?
Can we accelerate the train progress by preprocessing the data?

**Comment by GentleSmile** [comment]
The model calculates loss for one sample every time instead of a batch of samples. This simplifies development of the code at the expense of training time. Acceleration can be achieved by combining multiple samples into one batch instead of using 'for' loop.

**Comment by gilgamsh** [comment]
> The model calculates loss for one sample every time instead of a batch of samples. This simplifies development of the code at the expense of training time. Acceleration can be achieved by combining multiple samples into one batch instead of using 'for' loop.

Thank you very much.

**Comment by gilgamsh** [comment]
> The model calculates loss for one sample every time instead of a batch of samples. This simplifies development of the code at the expense of training time. Acceleration can be achieved by combining multiple samples into one batch instead of using 'for' loop.

I'm sorry  but which place should i modify to accelerate the training process?

**Comment by GentleSmile** [comment]
We do not recommend this acceleration because you will need to make modifications wherever the `For i in range(batch_size)` is included.
