### ISSUE TITLE
Question about goals sampling

### ISSUE THREAD

**Issue by ultimatedigiman** [Tsinghua-MARS-Lab/DenseTNT#15]
Hi,

In the ICCV paper,I noticed that you sampled dense goals along the **road**, as illustrated in your paper:
<img width="109" alt="image" src="https://user-images.githubusercontent.com/67790229/151542973-c46fe0d4-e80f-42f5-8d5b-55d9ad893370.png">

but in this code repo, you sampled goals along the lane **centerline**, which is as same as the vanilla TNT:
https://github.com/Tsinghua-MARS-Lab/DenseTNT/blob/398b8ceb5eb741d134c3e96a7515afef764d6a2f/src/dataset_argoverse.py#L125-L137

The parameter `include_beside` of function `get_subdivide_points()` will produce a denser goal set, but it seems you are not using it.

**Comment by GentleSmile** [comment]
This is a trick to reduce the number of sampled goals. The dense goal sampling is actually performed at [https://github.com/Tsinghua-MARS-Lab/DenseTNT/blob/398b8ceb5eb741d134c3e96a7515afef764d6a2f/src/modeling/decoder.py#L144](url).

**Comment by ultimatedigiman** [comment]
Thanks!
What does the comment "not compatible argo" in the sampling function ` get_neighbour_points()` mean?
https://github.com/Tsinghua-MARS-Lab/DenseTNT/blob/398b8ceb5eb741d134c3e96a7515afef764d6a2f/src/utils.py#L1226-L1229
