### ISSUE TITLE
Training time on Waymo

### ISSUE THREAD

**Issue by ShoufaChen** [Tsinghua-MARS-Lab/DenseTNT#19]
Hi,

Thanks for your awesome work.

How long did you train DenseTNT on the Waymo dataset? And how many GPUs (type) did you use?

**Comment by GentleSmile** [comment]
About 1-2 days with 8 GPUs. For each scene, we randomly select an agent to predict instead of predicting all agents.

**Comment by ShoufaChen** [comment]
What's the GPU type?

**Comment by GentleSmile** [comment]
2080Ti

**Comment by ShoufaChen** [comment]
Thanks.
