### ISSUE TITLE
Running this code for single-machine multi-GPUs

### ISSUE THREAD

**Issue by zhanglin010** [Tsinghua-MARS-Lab/DenseTNT#27]
Dear authors, thank you for releasing this wonderful code. Great work!

I am trying to run your code for single-machine multi-GPUs. I read PyTorch's docs and tutorials for data parallel training, but did not come up with a method. I am wondering whether you could give me some hints. Thank you.

**Comment by zhanglin010** [comment]
I compared this code with PyTorch's tutorials and find the difference is the backend. When the backend is changed from NCCL to gloo, the code can run in single-machine multi-GPUs case. But I did not figure out why this works.

**Comment by wentunshui** [comment]
> I compared this code with PyTorch's tutorials and find the difference is the backend. When the backend is changed from NCCL to gloo, the code can run in single-machine multi-GPUs case. But I did not figure out why this works.

hello, do you know how to run it in single-machine single-GPU case? thanks.

**Comment by zhanglin010** [comment]
> > I compared this code with PyTorch's tutorials and find the difference is the backend. When the backend is changed from NCCL to gloo, the code can run in single-machine multi-GPUs case. But I did not figure out why this works.
> 
> hello, do you know how to run it in single-machine single-GPU case? thanks.

As indicated in [this line of code](https://github.com/Tsinghua-MARS-Lab/DenseTNT/blob/a0e3b8a51aecf9f9046db4fb72e2793684c96e69/src/run.py#L305), set ’--distributed_training 1‘ should work.
