### ISSUE TITLE
Question About the dense goal sampling

### ISSUE THREAD

**Issue by SwagJ** [Tsinghua-MARS-Lab/DenseTNT#28]
Hi @GentleSmile, 

In your paper, the sampling strategy is densely sampled lines within 50 meters from initial position of target agent's trajectory. However, in your implementation, it seems that you firstly score the sparse goals and then dense the selected top 150 goals to generate dense goals from this 150 goals 
(https://github.com/Tsinghua-MARS-Lab/DenseTNT/blob/398b8ceb5eb741d134c3e96a7515afef764d6a2f/src/modeling/decoder.py#L144),  
which is different from your illustration in the paper. 
Is this true? If so, why change it?
I am looking forward to your reply. Thank you in advance

**Comment by GentleSmile** [comment]
There is a lane scoring module (see Section 3.2) in the paper in order to reduce the number of goal candidates. Here we use goal instead of lane because we found it is slightly better than lane scoring.

**Comment by SwagJ** [comment]
Hi @GentleSmile,

Thank you for your reply. Still I am a bit confused. If I understand the paper correctly, the sampling process should be 1) get all lanes with 50m from initial position of target agent. 2) score these lanes and select top K lanes 3) densify the lane to generate dense candidates 4) score them and do optimization(NMS or Goal set prediction+optimization). This is correct, right?

And in your implementation, the processs is simplified to 1) get all sparse candidate scores; 2) score them and select top 150 to densify them; 3)score the dense goals again. And the lane scoring part is somehow transformed to a hiddent hint to on goals' scores in form of attention? 
Is my understanding correct? I am looking forward to your reply. Thank you in advance.

**Comment by SwagJ** [comment]
Hi @GentleSmile, 

Thank you for your reply. It is quite clear now. But I do have one small question regarding to a detail in your code. In the code below
(https://github.com/Tsinghua-MARS-Lab/DenseTNT/blob/398b8ceb5eb741d134c3e96a7515afef764d6a2f/src/modeling/decoder.py#L184)
Why the target agent's feature from global graph is detached when computing trajectory completion loss? This is a bit of counter-intuitive for me. Thank you in advance.

**Comment by GentleSmile** [comment]
We found that the gradient from trajectory completion loss affects the performance of the goal probability estimation, so features are detached to prevent gradient backpropagation.

**Comment by SwagJ** [comment]
Hi @GentleSmile, 

Thank you very much for sharing this interesting finding. I will run ablation for that.
