### ISSUE TITLE
training Error

### ISSUE THREAD

**Issue by HMTJYQS** [Tsinghua-MARS-Lab/DenseTNT#3]
when  I follow the README.md running it, an error popped up saying StopIteration. Happended on  src/dataset_argoverse.py line 450:
 root, dirs, cur_files = os.walk(each_dir).__next__()
StopIteration

How to fix it? Thanks!

**Comment by John-HW-Cao** [comment]
see if "train/data" dir exists 

"train/data" is the default data path and if it doesn't exist, os.walk("train/data").next() will abort.

**Comment by HMTJYQS** [comment]
Thanks!  Model can work now.
