### ISSUE TITLE
The program is stuck

### ISSUE THREAD

**Issue by zsgj-Xxx** [Tsinghua-MARS-Lab/DenseTNT#35]
![微信图片_20221020182525](https://user-images.githubusercontent.com/55118073/196924633-2ade3992-5cbc-4a70-9f8a-4c59385be03f.png)
The progress bar will not be updated after arriving here
What could be the problem?

**Comment by GentleSmile** [comment]
What is the number of `core_num` ? It seems that data processing is too slow.

**Comment by zsgj-Xxx** [comment]
All parameters refer to those shown in readme. I've solved this problem， processed the dataset, excluding the length 110 example
