### ISSUE TITLE
Question about Outcomes

### ISSUE THREAD

**Issue by Zhimin-C** [Tsinghua-MARS-Lab/DenseTNT#39]
Thanks for the great job.
I have some questions about the definition of outcomes. What are stage_one_k and stage_one_recall in other_errors? What are FDE, ADE, DE@1, DE@2, and DE@3 mean?  Are FDE and ADE in outcomes represent the minFED1 and minADE1?
Thanks

**Comment by GentleSmile** [comment]
stage_one_k indicates the number of top K lanes we used for goal attention. FDE and ADE are boths error of the top 1 trajectory,  DE@1 is the displacment error at 1s in the future.

**Comment by Zhimin-C** [comment]
Thanks!
