### ISSUE TITLE
The doubt about anchor-free 

### ISSUE THREAD

**Issue by Xinchengzelin** [Tsinghua-MARS-Lab/DenseTNT#47]
I'm confused that the paper said DenseTNT is anchor-free, however, in the code, all the lane boundary point(goals_2D) is the model input, Is this contradictory？

**Comment by GentleSmile** [comment]
The meaning of anchor here is the same as in object detection, where anchors are used to regress bounding boxes. TNT uses anchors to regress final goals, which is anchor-based. In DenseTNT, no regression is needed.

**Comment by Xinchengzelin** [comment]
> e used to regress bounding boxes. TNT uses anchors to regress final goals, which is anchor-based. In DenseTNT, no regression is needed.

OK, Got it
