### ISSUE TITLE
Inquiry: Optimal Hardware Specs for Model Training

### ISSUE THREAD

**Issue by Sushmitha-93** [Tsinghua-MARS-Lab/DenseTNT#54]
Dear @GentleSmile ,

I hope you're well. I'm currently using your autonomous driving motion prediction code, but my training experiences suggest my current hardware specs may not be enough for training using the whole Argoverse 2 dataset.

Could you please advise on optimal specs for efficient model training? Any insights on storage, vCPUs, RAM, and GPU would be greatly appreciated.

My current Specs:
Storage: 150 GB
vCPUs: 8 Intel Xeon Gold 6238R
RAM: 80 GB
GPU: 8x RTX A6000 (48 GB each)

We are able to complete the data loading, but failing during training because one of the process fail before completion.

![image](https://github.com/Tsinghua-MARS-Lab/DenseTNT/assets/41836325/98e07ce6-dc32-4e18-8627-6bd115cd45fe)

Thank you for your time and assistance.

Best,
Sushmitha

**Comment by GentleSmile** [comment]
A simple solution is to set `GPU_NUM `to 2, then it only consumes 65G memory. To use 8 GPUs, The `Dataset` class needs to be modified to process data at runtime, instead of loading preprocessed dataset.

**Comment by Sushmitha-93** [comment]
Thank you so much for the suggestion @GentleSmile! We were able to finish training after selecting 2 GPUs. Really appreciate the quick reply :)

**Comment by Sushmitha-93** [comment]
Closing the issue
