### ISSUE TITLE
Loss function for sparse goal scoring

### ISSUE THREAD

**Issue by hanyang-hu** [Tsinghua-MARS-Lab/DenseTNT#60]
Hi. Thanks for the great work!

It seems that the implementation scores the sparse goals and chooses the top k (say k = 150) sparse goals to generate dense goals around them. May I ask why there is no loss function for the sparse goal scoring part? I can see that the lane scoring loss and dense goal scoring loss are computed.

**Comment by GentleSmile** [comment]
Top k goals and dense goals are both goals, and the loss of goals is calculated in `goals_2D_per_example_calc_loss`. So we don't need to calculate loss of top k goals seperately.

**Comment by hanyang-hu** [comment]
> Top k goals and dense goals are both goals, and the loss of goals is calculated in `goals_2D_per_example_calc_loss`. So we don't need to calculate loss of top k goals seperately.

I see, thanks for the response!
